### ISSUE TITLE
mycelium website

### ISSUE THREAD

**Issue by xmonader** [threefoldfoundation/www_mycelium#1]
We need a website for [mycelium](https://github.com/threefoldtech/mycelium) it's a technology similar to [yggrradsil](https://yggdrasil-network.github.io) for more context 

for any details / questions please check with @LeeSmet

**Comment by sasha-astiadi** [comment]
ok @xmonader

**Comment by sasha-astiadi** [comment]
maybe @Mik-TF can help

**Comment by Mik-TF** [comment]
@sasha-astiadi 

Happy to help in any way possible!
Let me know.

**Comment by sasha-astiadi** [comment]
https://github.com/threefoldtech/tf_operations/issues/1960 @Mik-TF @xmonader @ehab-hassan @LeeSmet 
actively building it at the moment will work with mik to fill in the content so we can leave @LeeSmet as reviewer , saving his time

**Comment by Mik-TF** [comment]
# General Template of Website

- homepage
  - headline sections (brief about the project)
- a section of about
  - the pros of the projects
  - how it works
- section about threefold
- section about manual

## About

* Talking in depths about the project, the pros, and how it works

**Comment by ehab-hassan** [comment]
@sasha-astiadi @Mik-TF I fixed responsive and spaces between all sections also I found some images inside the white border so I cropped it because it does not work well on mobile I pushed all at new branch development_fix_Responsve

**Comment by Mik-TF** [comment]
@LeeSmet 

If you can have a look at the dev version https://www2.mycelium.threefold.io/

It's really a broad overview of the project, but I think it's ready to be published, if that is what we want. 

If Lee thinks it's OK, we could then publish to www instead of www2

@sasha-astiadi

**Comment by Mik-TF** [comment]
@ehab-hassan
 
Could you set the www.mycelium.threefold.io website (with the master branch)? It's ready to be published as we already present it in the community call (www2 version).

**Comment by ehab-hassan** [comment]
@Mik-TF production updated by @PeterNashaat Thanks

**Comment by Mik-TF** [comment]
Great. Thanks @ehab-hassan and @PeterNashaat.
Closing this issue now that the first iteration of the Mycelium website is ready and in production mode.

If anything more is needed, we can create additional issues.

Thanks everyone for the work and time.
